### PR TITLE
New blog post on the OPAM-based build system

### PR DESCRIPTION
**Pull request by AltGr**

### CODE REVIEW

**Comment by AltGr** [comment]
Waiting for review to make sure it won't be taken the wrong way (if so, better to just dismiss !) :)

**Comment by avsm** [comment]
To be honest, the first impression made me groan, since it still basically has the broken model of shipping a bytecode blob to bootstrap (brittle to host OCaml version, and won't fly with upstream distribution at all, who will be forced to maintain an `ocamlbuild` or `OCamlMakefile` version yet again.  The Assemblage and Jenga solutions to this are to generate a bootstrap `Makefile`.

It's also not entirely clear why the OPAM parallelisation engine would make a good build system -- does it support dynamic discovery, caching of dependencies, and does a build system leverage its unique capabilities (the CUDF solving engine)?  On the other hand, there are some *very* cool things to highlight, such as pulling out the `OpamParallel` module into a separate library for parallel computation (along with the Dot debugging abilities).  A blog post doing the latter, and then introducing `opam2src` as a separate tool.  

Another use that's emerging for "opam as a build system" is actually as a scripting engine -- in the MirageOS, we're using it to run shell scripts that depend on each other to run tests, and the same is true of the performance benchmarking suite at OCamlPro (although that is difficult to parallelise for obvious reasons).

Finally, given the ongoing work on Assemblage by Thomas Gazagnaire and Daniel Bunzli, I'd suggest that the `opam-build` term deserves some consensus on opam-devel before assigning it to `opam2src`...

**Comment by samoht** [comment]
I don't like April fools :p

**Comment by avsm** [comment]
Booo! Play along :-P

**Comment by rdicosmo** [comment]
Thanks Louis, very well designed April's fool message, made me smile :-)

--
Roberto

2015-04-01 3:17 GMT+02:00 Louis Gesbert <notifications@github.com>:

> ------------------------------
> You can view, comment on, or merge this pull request online at:
>
>   https://github.com/ocaml/platform-blog/pull/30
> Commit Summary
>
>    - New blog post on the OPAM-based build system
>
> File Changes
>
>    - *A* opam-builder.md
>    <https://github.com/ocaml/platform-blog/pull/30/files#diff-0> (66)
>
> Patch Links:
>
>    - https://github.com/ocaml/platform-blog/pull/30.patch
>    - https://github.com/ocaml/platform-blog/pull/30.diff
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ocaml/platform-blog/pull/30>.
>



-- 
Roberto Di Cosmo

------------------------------------------------------------------
Professeur               En delegation a l'INRIA
PPS                      E-mail: roberto@dicosmo.org
Universite Paris Diderot WWW  : http://www.dicosmo.org
Case 7014                Tel  : ++33-(0)1-57 27 92 20
5, Rue Thomas Mann
F-75205 Paris Cedex 13   Identica: http://identi.ca/rdicosmo
FRANCE.                  Twitter: http://twitter.com/rdicosmo
------------------------------------------------------------------
Attachments:
MIME accepted, Word deprecated
      http://www.gnu.org/philosophy/no-word-attachments.html
------------------------------------------------------------------
Office location:

Bureau 320 (3rd floor)
Batiment Sophie Germain
Avenue de France
Metro Bibliotheque Francois Mitterrand, ligne 14/RER C
-----------------------------------------------------------------
GPG fingerprint 2931 20CE 3A5A 5390 98EC 8BFC FCCA C3BE 39CB 12D3

**Comment by Drup** [comment]
Nice ! Here's the xkcd for you: https://xkcd.com/927/ ;)

**Comment by AltGr** [comment]
@drup yeah, I got tired of seeing it quoted too often ;)

**Comment by AltGr** [comment]
April 1st is over, closing :D

**Comment by AltGr** [comment]
To clarify a bit, I _do_ think that the parallel engine might make a good component of a build system, maybe with some modifications ; I did try a very quick prototype going that way, and we are discussing possible usage by Assemblage. It's probably not the most difficult part of a build system though.

Defining a local opam repository to build a project was just nonsense, as was the rest of the post :)
The words "brand" and "marketting" getting out of my keyboard in the introduction were good hints that something wasn't right ;)

**Comment by samoht** [comment]
You should not joke with new build systems released in 1st of April: https://github.com/def-lkb/ocamp :p

**Pull request closed without merging**
