### PR TITLE
Correct the URL for the platform mailing list

### PR DESCRIPTION
**Pull request by amirmc**
This should be merged when @AltGr has mailed the list

### CODE REVIEW

**Comment by hannesm** [comment]
you're right, I just mailed to that list (since @AltGr isn't on IRC ;) http://lists.ocaml.org/pipermail/platform/2015-June/000595.html feel free to merge whenever you wish

**Comment by amirmc** [comment]
Seems we both forwarded the email :)
I didn't notice this until my mail client caught up.

@samoht d'you happen to know how often the blog is refreshed/rebuilt? It'll display the incorrect link until that happens.

**Comment by samoht** [comment]
every hour I think. see https://opam.ocaml.org/lastlog.txt

**Comment by amirmc** [comment]
Can we force it?  I've already had to point two people to the correct list. I'd like to avoid doing that again if possible.

**Comment by samoht** [comment]
next build is in a few minuts

**Comment by amirmc** [comment]
Ah, ofc. I can't tell time :-P

**Comment by hannesm** [comment]
it's updated now..

**Comment by amirmc** [comment]
Kinda glad we got that done fairly quick.  Post is now at the top of HackerNews.

**Pull request merged**
