### PR TITLE
minor: gender-neutral attacker

### PR DESCRIPTION
**Pull request by gasche**
English is amusingly gender-neutral, and I think it's good to preserve that property -- this was the only change needed to do so in this text.

### CODE REVIEW

**Comment by amirmc** [comment]
Well spotted.  Could you change it to 'they'?  That's also acceptable and maintains readability.

**Comment by gasche** [comment]
"for which they is not the real maintainer" is highly controversial grammar-wise. I prefer "he or she", but can update the PR with "for which they are not the real maintainer" if that suits you better.

**Comment by amirmc** [comment]
Sorry, I did mean "for which they are..." as you point out. Yes, please do make the edit and I'll merge.

**Comment by gasche** [comment]
Updated.

**Comment by amirmc** [comment]
Thanks!

**Pull request merged**
