### PR TITLE
add security post on 2.1.5

### PR DESCRIPTION
**Pull request by hannesm**
from @reynir and myself.

### CODE REVIEW

**Comment by tmattio** [comment]
Thanks @hannesm! Same heads up as in https://github.com/ocaml/platform-blog/pull/87: we're now featuring the platform blog in ocaml.org. The release announcements are now in the [OCaml Changelog](https://ocaml.org/changelog) and the blog posts are in the [OCaml Planet blog](https://ocaml.org/blog). Do you want to open a PR on ocaml.org with this blog post? These go in https://github.com/ocaml/ocaml.org/tree/main/data/planet/ocamlorg.

**Comment by hannesm** [comment]
@tmattio thanks for your comment, but I'm a bit lost, is there any documentation how to move forward?

Last time I opened https://github.com/ocaml/ocaml.org/issues/242 and thought that RSS/Atom would be automatically harvested and integrated into the OCaml planet.

Would you be able to clarify the process for "blog post", "planet blog", and "chagelog"? If I understand you correctly, each article now needs to be present in git repos thrice (or twice) -- which formats and UUIDs should be used? And there's really no syndication automation?

**Comment by tmattio** [comment]
> Would you be able to clarify the process for "blog post", "planet blog", and "changelog"?

We're [migrating opam.ocaml.org to ocaml.org](https://github.com/ocaml/infrastructure/issues/26). This started with the central package documentation (at https://ocaml.org/packages), now with the Platform blog, and next with the opam documentation.

The Platform blog was essentially composed of release announcements and blog posts. The release announcements have been integrated into the OCaml Changelog and the blog posts have been integrated into the Planet blog. The Planet is, under the hood, indeed an aggregate of RSS feeds, but since we don't have a feed for Platform posts, they are hosted on ocaml.org directly, e.g. https://ocaml.org/blog/signing-the-opam-repository.

> If I understand you correctly, each article now needs to be present in git repos thrice (or twice)

Until we sunset opam.ocaml.org, I think it'd be best to cross-post the posts and announcements on the Platform blog and ocaml.org. We should make an announcement when we're ready to sunset opam.ocaml.org.

> which formats and UUIDs should be used?

The markdown file you added here is good, the metadata format is slightly different on ocaml.org, but otherwise copy-pasting it is enough. Here's an example of the metadata for another Platform post on ocaml.org:
```
---
title: "Signing the OPAM repository"
authors: [ "Louis Gesbert", "Hannes Mehnert" ]
date: "2015-06-05"
description: "Proposal for a secure distribution of OCaml packages"
---
```

> And there's really no syndication automation?

There is for community RSS feeds, and your blog is part of the syndicated RSS feeds. They can be added here: https://github.com/ocaml/ocaml.org/blob/main/data/planet-sources.yml

Hope this clarifies things! Let me know if anything is still unclear

**Comment by hannesm** [comment]
Thanks for your reply.

> > Would you be able to clarify the process for "blog post", "planet blog", and "changelog"?
> 
> We're [migrating opam.ocaml.org to ocaml.org](https://github.com/ocaml/infrastructure/issues/26). This started with the central package documentation (at https://ocaml.org/packages), now with the Platform blog, and next with the opam documentation.

I didn't know that.

> The Platform blog was essentially composed of release announcements and blog posts. The release announcements have been integrated into the OCaml Changelog and the blog posts have been integrated into the Planet blog. The Planet is, under the hood, indeed an aggregate of RSS feeds, but since we don't have a feed for Platform posts, they are hosted on ocaml.org directly, e.g. https://ocaml.org/blog/signing-the-opam-repository.

Does https://opam.ocaml.org/blog/feed.xml not count?

> > If I understand you correctly, each article now needs to be present in git repos thrice (or twice)
> 
> Until we sunset opam.ocaml.org, I think it'd be best to cross-post the posts and announcements on the Platform blog and ocaml.org. We should make an announcement when we're ready to sunset opam.ocaml.org.
> 
> > which formats and UUIDs should be used?
> 
> The markdown file you added here is good, the metadata format is slightly different on ocaml.org, but otherwise copy-pasting it is enough. Here's an example of the metadata for another Platform post on ocaml.org:
> 
> ```
> ---
> title: "Signing the OPAM repository"
> authors: [ "Louis Gesbert", "Hannes Mehnert" ]
> date: "2015-06-05"
> description: "Proposal for a secure distribution of OCaml packages"
> ---
> ```

I see. I'll try to find time for ocamlorg once this PR here is merged. I won't promise anything.

> > And there's really no syndication automation?
> 
> There is for community RSS feeds, and your blog is part of the syndicated RSS feeds. They can be added here: https://github.com/ocaml/ocaml.org/blob/main/data/planet-sources.yml
> 
> Hope this clarifies things! Let me know if anything is still unclear

**Comment by tmattio** [comment]
> Does https://opam.ocaml.org/blog/feed.xml not count?

It does, as the goal is to sunset opam.ocaml.org, it makes little sense to add a dependency on the opam RSS feed to migrate it to ocaml.org.

> I see. I'll try to find time for ocamlorg once this PR here is merged. I won't promise anything.

Thanks! It'd be ideal to have concurrent PRs so we are not constantly tracking which posts we forgot to replicate to ocaml.org.

**Comment by rjbou** [comment]
thanks!

**Pull request merged**
